LibreBooking/app

plugins/Authentication/Saml/adSAML.php
Following guidelines from the SimpleSAML documentation (https://simplesamlphp.org/docs/stable/simplesamlphp-sp-api#section_0_1), a cleanup is necessary after calling the SimpleSAML api to authenticate in order to use the correct php Session.
Without cleanup, the USER_SESSION is saved in the SimpleSAML Session and checks performed during the `Page.IsAuthenticated()` fail, looking in a different session and triggering a redirect loop
=> Fix PHP session conflict with SimpleSAML

lang/de_de.php
Having seen a missing translation in the Resource Panel for 'NextReservation' I have taken the chance to add some more strings that appeared to be missing.
=> TRANSLATION - Extend strings for German (de_de)

Domain/Access/PaymentRepository.php, Domain/CreditCost.php, Pages/Admin/ManagePaymentsPage.php, Pages/Credits/CheckoutPage.php, Pages/Credits/UserCreditsPage.php, Presenters/Admin/ManagePaymentsPresenter.php, Presenters/Credits/CheckoutPresenter.php, Presenters/Credits/UserCreditsPresenter.php, Presenters/Reservation/ReservationCreditsPresenter.php, Web/scripts/admin/payments.js, Web/scripts/user-credits.js, database_schema/upgrades/2.8/schema.sql, lang/en_us.php, lang/es.php, lib/Database/Commands/Commands.php, lib/Database/Commands/Queries.php, lib/Server/FormKeys.php, lib/Server/QueryStringKeys.php, tests/Domain/Payment/PaymentRepositoryTest.php, tests/Presenters/Admin/ManagePaymentsPresenterTest.php, tests/Presenters/CheckoutPresenterTest.php, tpl/Admin/Payments/manage_payments.tpl, tpl/Credits/checkout.tpl, tpl/Credits/user_credits.tpl
Hi @effgarces, thanks for maintaining this project!
I needed support for multiple payment configurations to offer discounts when a user buys several credits at the same time. This pull request implements this feature.
The main changes are a payment configuration table where admins can create, update, read and delete payment configurations:
And a selector for users to buy a pack of credits at a different cost:
This is my first time working on this codebase, so it probably needs a review. Things I'm not sure about:
- Database migration: I ran the commands manually and wrote them in `database_schema/upgrades/2.8/schema.sql`, will this work for upgrades?
- Tests: I slightly modified some of them, but I don't know how to run them.
- Did I update the translations properly? (for others to work …
=> Add support for multiple payment configurations

Dockerfile, doc/INSTALLATION.md, lib/Database/Commands/Queries.php
A fix for a PHP 8 warning (missing column when querying the database) and a change to the DocumentRoot of the Dockerfile to avoid issues.
I also improved the installation docs to note that `composer install` is now required to download vendored dependencies before uploading the app to the server. Required because https://github.com/LibreBooking/app/pull/160 removed old dependencies by using composer to manage them.
=> Fix missing query column and better docker setup

doc/INSTALLATION.md
This change to the installation doc recommends enabling the **headers** and **rewrite** modules for an **Apache2** server environment and closes #177 . The rewrite module is used to manipulate url's; the headers module is used to control and modify http request and response headers. Both modules are required for proper operation of LibreBooking.
=> Revised installation document to recommend enabling required Apache2 modules.

WebServices/ResourcesWebService.php
With GetAvailability(resourceId = null) the GET query parameter is not reflected in the response. Maybe this was intermittently set since there is an alternative route for GetAvailability that uses a static URI instead of a query parameter for resourceId. See /Web/Services/index.php . This fix prefers the route with explicit query params for resourceId and dateTime over the static route. Hence, the alternative route should be disabled with a subsequent change.
Please feel free to correct me if I misunderstood the function signature or if there is a way to enable both routes. I have tried but the Slim framework seems not to allow alternative signatures on the same function.
In addition, I have set the time span for the delivered availability to 7 instead of 30 days as described in the API …
=> BUGFIX - API: reflect qry param in GetAvailability

composer.json, docker/Dockerfile, lib/WebService/Slim/SlimServiceRegistration.php, lib/external/Slim/Http/Util.php
Fixes some deprecations issues in the REST api on PHP8. Most problematic is the use of `get_magic_quotes_gpc()`, which has been removed in PHP8.0.
LibreBooking runs on Slim framework V2, which has been EOL for some time now. It is recommended to upgrade to Slim V4 at some point (along with other third party libs like Pearc components). But this will take considerably more effort.
=> Fix REST API for PHP8

lib/Common/Date.php, tests/Infrastructure/Common/DateTest.php
This fix is for issue the https://github.com/LibreBooking/app/issues/173 .
I added a couple of tests related with month and year handling and the current days tests are failing, so it was not necessary to add more tests, just fix them was ok.
I don't know if exists some guidelines to contribute, the README.md in /doc was not helpful to make this PR, but just let me know if I have to modify something.
=> Plus operator fixed with negative numbers in Date Add methods

lib/Common/Date.php
Bug: Implicit conversion from float 1.5 to int loses precision
=> Fix issue 212

lib/Common/Date.php
Recently a fix for date handling in PHP 8.2 was added in PR #209 which resolves an issue where the Schedule previous date buttons were always progressing forwards rather than back.
@jplagostena correctly traced this back to the handling of the +/- in PHP 8.2 and added a fix.
Unfortunately this fix breaks on 8.1 and lower and introduces the same issue in that environment. While obviously the intent is to support later versions of PHP, I think consistent behaviour across versions is desirable.
I've added a very simple addition to the work by @jplagostena to use the absolute value passed in, once the correct + or - prefix has been determined. This means there is only ever a single plus or minus operator added, and avoids the issue with double negatives across all PHP versions.
Here are some …
=> Fix for inconsistent DateTime behaviour between PHP versions

Pages/ResourceDisplayPage.php, Presenters/ResourceDisplayPresenter.php, Web/css/booked.css, Web/scripts/resourceDisplay.js, lib/Config/ConfigKeys.php, tests/Presenters/ResourceDisplayPresenterTest.php, tpl/ResourceDisplay/resource-display-resource.tpl, tpl/ResourceDisplay/resource-display-shell.tpl
This feature adds the possibility to choose a later date in the public view of a resource currently limited to the current day only.
- New configuration setting: `$conf['settings']['privacy']['public.future.days']` which default to 1 to get the current behavior
- Date picker on the public resource page which reloads the page accordingly and displays the reservations of the selected day (adds a couple of refresh indicators along the way)
- Server side check to avoid bypass on the maximum bookable day
- Basic error message when the date is not authorized (<- could be improved to be region-based)
_Due to the fact that the page is a mix of Smarty templates and static php page loaded by ajax, the date picker is created in the template and displayed over the rest of page as a floating div_
=> Public resource booking for a longer period

lib/Config/Configurator.php
Without adding mysqli_report() to the config file the config file is automatically broken on hitting "Update" on the Web/admin/manage_configuration.php page.
=> Add mysqli_report() to the config file.

Presenters/RegistrationPresenter.php
homepage default value should come from the application settings and not forced to 1 (ie. Dashboard)
=> Fix homepage default value in self-register form

lib/Application/Authentication/Registration.php, plugins/Authentication/Ldap/Ldap2Wrapper.php
- Fix debug message when group is not synced: user and group names are inverted
- Add argument `'all'` to function getValue to ensure that it always return an array, otherwise the following statement with array_map will trigger an exception
=> Ldap groups sync: miscellaneous fixes

lib/Application/Authentication/Registration.php
- Before modification: synch worked only for librebooking groups whose name matched the LDAP dn, as in `cn=librebooking.users,ou=groups,dc=example,dc=org`.
- After modification: sync works also for librebooking groups whose name matches the LDAP cn, as in `librebooking.users`
=> Enhance LDAP group synching

config/config.devel.php, config/config.dist.php
- Fix the directive for header `Strict-Transport-Security`
True | false is not a valid directive for the STS header. Valid directives are:
- max-age
- includeSubDomains
- preload
Check https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security
=> Fix directive for Strict-Transport-Security

Presenters/Admin/ManageResourceGroupsPresenter.php
Fix wrong call to Log::Debug
When deleting a resource group, Log::debug only needs the nodeId
=> Fix resource-group deletion

lib/Common/Logging/Log.php
1. Function **debug()** should call Monolog method `Logger->debug()` instead of method Logger->info()
2. Method `Logger->PushHandler` should be invoked with the error level which is in line with the settings file config.php
3. Functions **debug()** and **error()** should not test the error level. They should let Monolog decide whether to log the message or not, based on the log level specified on the handler (see above):
- If log level is **debug**, then debug and error message should be displayed
- If log level is **error**, then only error messages are displayed
=> Review the logging feature (Log.php)

lib/Application/Authentication/Authentication.php
- Use easier-to-read statements
- Failed user authentication triggers an error logging
=> Review user authentication logging

lib/Common/Logging/Log.php
The following data will be added to the Monolog `app` channel:
- 'REQUEST_URI'
- 'REMOTE_ADDR'
- 'REQUEST_METHOD'
- 'SERVER_NAME'
- 'HTTP_REFERER'
- 'HTTP_USER_AGENT'
The `REMOTE_ADDR` enables the future implementation of a `fail2ban` jail.
=> Use the Monolog-provided WebProcessor to log extra data

lib/Database/MySQL/MySqlConnection.php
I am working with a derived transaction save database class which uses multi queries. The current implementation of multi queries does not work.
Results must be freed after each query of a multi query!
=> MultiQuery - free results after each query

.htaccess
The rewrite rules for `REQUEST_FILENAME ` allow direct file access to all existing paths that don't match the first rule.
For example you can read the git config of an instance simply be entering
> https:://librebooking.example.com/.git/config
in your browser.
=> Close a critical vulnerability hole in .htaccess

Domain/Access/IResourceRepository.php, Domain/Access/ResourceRepository.php, Pages/Page.php, Pages/ResourceViewerViewResourcesPage.php, Pages/ScheduleViewerViewSchedulesPage.php, Presenters/ViewResourcesPresenter.php, Presenters/ViewSchedulesPresenter.php, Web/view_resources.php, Web/view_schedules.php, lang/en_us.php, lang/pt_pt.php, lib/Database/Commands/Commands.php, lib/Database/Commands/Queries.php, tpl/Admin/Resources/view_resources.tpl, tpl/Admin/Schedules/view_schedules.tpl, tpl/globalheader.tpl
Added a new feature that enables users to check resources and schedules without requiring administrator privileges. This feature mirrors the capabilities of the manage resources and schedules functions, but doesn't allow edits and displays only those resources and schedules accessible to the user or groups they belong to, based on their permissions (view or full access). If a resource is hidden, it remains invisible to the user, even if they possess the necessary permissions (Issue #90).
This feature only has the English and Portuguese translations implemented.
=> User Resource and Schedule Views

lib/Email/Messages/ReservationEmailMessage.php
Provide `ScheduleId` for reservation templates. So it's possible to add schedule dependent information in the email template.
```smarty
{if $ScheduleId == 18 }
Important schedule information
{/if}
```
=> Provide ScheduleId in reservation email

plugins/Authentication/Saml/adSAML.php
I removed the constructor because I think is deprecated in the last simpleSaml version. Without it it works just fine.
=> Removed constructor deprecated

WebServices/SchedulesWebService.php
The class `ScheduleWebServiceView` had an abstract method `BindViewableResourceReservation` which was not implemented. This caused API access to fail with an error like:
```
[php:error] [pid 84] [client 10.89.0.25:59502] PHP Fatal error:  Class ScheduleWebServiceView contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (ISchedulePage::BindViewableResourceReservations) in /var/www/html/WebServices/SchedulesWebService.php on line 169
```
Implement the missing method as a `no-op` method.
Closes: #343
=> fix(api): API calls were broken due to abstract method

WebServices/Responses/ResourceResponse.php
When getting the values from the API return `TimeInterval` use the `ToShortString` method. As when sending the data back the API does not accept the longer forms of TimeInterval.
This means we receive the values from the API as '1d2h3m' instead of '1 days 2 hours 3 minutes'
=> fix: use `TimeInterval:ToShortString` in API response

WebServices/ResourcesWriteWebService.php
The `Update()` method had debug messages calling it the `Create()` method. Fix that.
=> chore: fix log message to correct method name

.github/workflows/lint-and-analyse-php.yml, ci/ci-phplint, lib/external/FeedWriter/FeedWriter.php, lib/external/pear/Config/Container/IniCommented.php, lib/external/pear/Config/Container/XML.php, lib/external/pear/Event/Dispatcher.php, lib/external/pear/System.php
This was inspired by:
https://github.com/phpmyadmin/phpmyadmin/blob/b094f337466a1188ad755b33be5a7b7b25a70916/.github/workflows/lint-and-analyse-php.yml
Resolve issues flagged by the syntax error checker:
```
PHP Parse error:  syntax error, unexpected token "new" in ./lib/external/pear/Event/Dispatcher.php on line 249
Errors parsing ./lib/external/pear/Event/Dispatcher.php
PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in ./lib/external/pear/System.php on line 238
Errors parsing ./lib/external/pear/System.php
PHP Parse error:  syntax error, unexpected token "new" in ./lib/external/pear/Config/Container/XML.php on line 134
Errors parsing ./lib/external/pear/Config/Container/XML.php
PHP Fatal error:  Array and string offset access syntax with …
```
=> ci: create an initial CI that runs a syntax check

WebServices/Requests/Resource/ResourceRequest.php
PHP 8.2 has deprecated dynamic properties. So need to ensure the properties are defined.
Added:
bufferTime
groupIds
icsUrl
minNoticeAdd
minNoticeDelete
minNoticeUpdate
typeId
=> fix: add missing properties to ResourceRequest

WebServices/AuthenticationWebService.php, WebServices/Controllers/ReservationSaveController.php
The attribute `ReservationControllerResult.requiresApproval` needs to be declared or PHP 8.2 will fail as dynamic attributes are deprecated.
Closes: #242
=> fix: declare `ReservationControllerResult.requiresApproval`

Domain/Access/IResourceRepository.php, Domain/Access/ResourceRepository.php, Web/Services/index.php, WebServices/ResourcesWebService.php, lib/Common/ServiceLocator.php
Previously API users could see all the resources, even if the user was not given permission to some of the resources.
Now non-Admin users will only see the resources that they have access to via their direct access or group access.
=> fix(api): restrict resources seen by non-Admin users

lib/external/pear/PEAR.php
This function has been DEPRECATED as of PHP 7.2.0, and REMOVED as of PHP 8.0.0. Relying on this function is highly discouraged.
```
PHP Fatal error:  Uncaught Error: Call to undefined function each() in lib/external/pear/PEAR.php:781\nStack trace:\n#0 [internal function]: _PEAR_call_destructors()\n#1 {main}\n  thrown in lib/external/pear/PEAR.php on line 781
```
Ref: https://www.php.net/manual/en/function.each.php
=> fix: deprecated each() function

lib/Server/Server.php
UserSession is saved in session:
+ When we put it to session, it is UserSession object
+ When we get it from session, we need to cast it to UserSession class
=> fix: cast UserSession class from session object

lib/external/pear/PEAR.php
Error was:
Creation of dynamic property PEAR_Error::$callback is deprecated
=> chore: fix dynamic property error

lib/external/pear/PEAR.php
Backport: https://github.com/pear/pear-core/pull/135
=> chore: fix calling `get_class()` without arguments

plugins/Authentication/Ldap/LDAP2/Search.php
When using Ldap authentication, these deprecation warnings were being sent as part of the API response. This corrupted the expected JSON response.
=> chore(ldap): fix deprecation warnings about return types

config/config.devel.php, config/config.dist.php, lib/Application/Authentication/CaptchaService.php, lib/Config/ConfigKeys.php
The default request method of recaptcha is _post_. This uses the method `file_get_contents` to execute the request. This [might be blocked](https://stackoverflow.com/questions/55978690/recaptcha-error-code-connection-failed-on-verification).
This PR makes the request method configurable. The default is still _post_. However I changed it to curl in the default config file.
I also fixed the logging.
=> Make request method configurable

plugins/Authentication/Ldap/Ldap2Wrapper.php
Some ldap servers don't return user email 
When we Authenticate --> PopulateUser first time --> Email will return empty
We will try PopulateUser second time --> Email will return `uid@dc`
=> Fix ldap server does not return email

tpl/Reservation/approve.tpl, tpl/Reservation/edit.tpl
Possibly connected with issue #265.
Currently, when administrator deletes a reservation, there is a pop-up form which allows to add a deletion reason which is sent as a notification.
The same form appears when admin wants to reject a pending reservation. But unlike deleting an approved appointment, the template for the text field misses a `deleteReason` class, which results in empty delete reason in notification e-mail.
This PR fixes that behaviour, making it work in both cases.
=> fix: no delete reason when rejecting reservation
